# SPDX-FileCopyrightText: 2024-2025 Rafael V. Volkmer <rafael.v.volkmer@gmail.com>
# SPDX-License-Identifier: MIT

name: "📚 Documentation Issue"
description: "Report a problem or missing information in the documentation."
title: "[DOCS] "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Description  
        Describe what is wrong or missing in the documentation.
        
        - Which page or file is affected?  
        - What is unclear, incorrect, outdated, or missing?  

  - type: textarea
    id: description
    attributes:
      label: Documentation Issue Description
      placeholder: "Explain the problem or gap in the documentation."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 📍 Location

  - type: textarea
    id: location
    attributes:
      label: Location of the issue
      description: "Which file, page, or section is affected?"
      value: |
        - File / page: (e.g. README.md, docs/usage.md)
        - Section / heading: (if applicable)
        - Link (if published online):
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## ✅ Expected Documentation  
        What would you expect the documentation to say or clarify?

  - type: textarea
    id: expected
    attributes:
      label: Expected or Correct Documentation
      placeholder: "Describe the expected correct explanation or behavior."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 💡 Suggested Fix (optional)

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested fix (optional)
      description: "If you already know how it should be corrected, draft the fix."
      render: markdown
      placeholder: "<!-- suggested replacement text -->"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 📎 Additional Context  
        Add any other context that might help:
        
        - Screenshots  
        - References  
        - Related standards/papers/blog posts  
        - Notes about versions or configurations that affect the docs  

  - type: textarea
    id: context
    attributes:
      label: Additional context
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## ✍️ Signed-off-by (DCO)
        
        If you intend to submit a PR fixing this documentation issue and wish
        to comply with the Developer Certificate of Origin (DCO), include your
        own line below:

        ```
        Signed-off-by: <Your Name> <your.email@example.com>
        ```
