name: Docker Multi-Arch CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [
                    linux/arm64,
                    linux/amd64,
                    linux/amd64/v2,
                    linux/amd64/v3,
                    linux/arm/v7,
                    linux/arm/v6,
                    linux/riscv64,
                    linux/ppc64le,
                    linux/386,
                  ]
        build_mode: [ 
                      Debug,
                      Release
                    ]

    concurrency:
      group: docker-${{ github.ref }}-${{ matrix.platform }}-${{ matrix.build_mode }}
      cancel-in-progress: true

    env:
      BUILD_TYPE: ${{ matrix.build_mode }}
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Prepare build.sh
        run: chmod +x ./build.sh

      - name: Build image (${{ matrix.platform }}, ${{ matrix.build_mode }})
        run: |
          ./build.sh ${{ matrix.build_mode }} --docker --platform ${{ matrix.platform }}

      - name: Inspect image
        run: docker images | grep libmemalloc

      - name: Show binaries
        run: ls -l bin/${{ matrix.build_mode }}
