name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Prepare doc script
        run: chmod +x ./doc.sh

      - name: Generate documentation
        run: ./doc.sh

      - name: Upload HTML docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: build/docs/html
