name: Docker Image CI

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - build_mode: Release
          - build_mode: Debug

    env:
      DOCKER_BUILDKIT: 1
      BUILD_TYPE: ${{ matrix.build_mode }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Build image (${{ env.BUILD_TYPE }})
        run: |
          sudo ./build.sh ${{ env.BUILD_TYPE }} --docker

      - name: List local images
        run: docker images libmemalloc:${{ env.BUILD_TYPE }}

      - name: Show extracted files
        run: ls -l ./bin/${{ env.BUILD_TYPE }}

      - name: Upload libraries (.so / .a)
        if: env.ACTIONS_RUNTIME_TOKEN
        uses: actions/upload-artifact@v4
        with:
          name: libmemalloc-${{ env.BUILD_TYPE }}
          path: |
            bin/${{ env.BUILD_TYPE }}/*.so
            bin/${{ env.BUILD_TYPE }}/*.a
